{{- range $serviceName, $v := .Values -}}
{{- if (or (eq $serviceName "raster") (eq $serviceName "stac") (eq $serviceName "vector")) }}
{{- if index $v "enabled" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $serviceName }}-envvar-configmap
data:
  {{- range $envKey, $envValue := index $v "settings" "envVars" }}
  {{ upper $envKey }}: "{{ $envValue }}"
  {{- end }}
---
{{/* END: if index $v "enabled" */}}
{{- end }}
{{/* END: if (or (eq $serviceName "raster") (eq $serviceName "stac") (eq $serviceName "vector")) */}}
{{- end }}
{{/* END: range $serviceName, $v := .Values*/}}
{{- end }}
